name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
  
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Build
      run: yarn build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: "public/"

  
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Unit tests
      run: yarn test
    - name: Publish test results
      uses: mikepenz/action-junit-report@v6
      if: success() || failure()
      with:
        report_paths: 'reports/jest-junit.xml'
  
  integration-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
    - name: Integration tests
      run: yarn test:e2e
    - name: Publish test results
      uses: mikepenz/action-junit-report@v6
      if: success() || failure()
      with:
        report_paths: 'reports/cypress-junit.xml'
